/// Channel names shared with the renderer. These mirror
/// `src/shared/ipc-channels.ts` verbatim; the contract fixtures guard drift.
public enum BridgeChannels {
  public static let bootstrap = "codepi:bootstrap"
  public static let addProject = "codepi:add-project"
  public static let toggleProject = "codepi:toggle-project"
  public static let createThread = "codepi:create-thread"
  public static let deleteThread = "codepi:delete-thread"
  public static let selectThread = "codepi:select-thread"
  public static let openThread = "codepi:open-thread"
  public static let restartThread = "codepi:restart-thread"
  public static let restartThreadWithoutCapabilities = "codepi:restart-thread-without-capabilities"
  public static let sendMessage = "codepi:send-message"
  public static let abortThread = "codepi:abort-thread"
  public static let setModel = "codepi:set-model"
  public static let setThinkingLevel = "codepi:set-thinking-level"
  public static let getCapabilities = "codepi:get-capabilities"
  public static let setCapabilityEnabled = "codepi:set-capability-enabled"
  public static let getCommands = "codepi:get-commands"
  public static let compactThread = "codepi:compact-thread"
  public static let setAutoCompaction = "codepi:set-auto-compaction"
  public static let setAutoRetry = "codepi:set-auto-retry"
  public static let getUsageDashboard = "codepi:get-usage-dashboard"
  public static let searchProjectFiles = "codepi:search-project-files"
  public static let getRecentFiles = "codepi:get-recent-files"
  public static let pickAttachments = "codepi:pick-attachments"
  public static let listPromptTemplates = "codepi:list-prompt-templates"
  public static let savePromptTemplate = "codepi:save-prompt-template"
  public static let deletePromptTemplate = "codepi:delete-prompt-template"
  public static let getHistory = "codepi:get-history"
  public static let branchThread = "codepi:branch-thread"
  public static let updateThread = "codepi:update-thread"
  public static let duplicateThread = "codepi:duplicate-thread"
  public static let restoreThread = "codepi:restore-thread"
  public static let purgeThread = "codepi:purge-thread"
  public static let searchThreads = "codepi:search-threads"
  public static let exportThread = "codepi:export-thread"
  public static let getChanges = "codepi:get-changes"
  public static let setFileStaged = "codepi:set-file-staged"
  public static let commit = "codepi:commit"
  public static let applyToMain = "codepi:apply-to-main"
  public static let openInEditor = "codepi:open-in-editor"
  public static let listWorkspaceFiles = "codepi:list-workspace-files"
  public static let readWorkspaceFile = "codepi:read-workspace-file"
  public static let openTerminal = "codepi:open-terminal"
  public static let writeTerminal = "codepi:write-terminal"
  public static let resizeTerminal = "codepi:resize-terminal"
  public static let closeTerminal = "codepi:close-terminal"
  public static let openPreview = "codepi:open-preview"
  public static let setPreviewBounds = "codepi:set-preview-bounds"
  public static let previewAction = "codepi:preview-action"
  public static let closePreview = "codepi:close-preview"
  public static let openSettings = "codepi:open-settings"
  public static let getSettings = "codepi:get-settings"
  public static let saveSettings = "codepi:save-settings"
  public static let validatePi = "codepi:validate-pi"

  // Event streams pushed to the renderer.
  public static let threadEvent = "codepi:thread-event"
  public static let menuAction = "codepi:menu-action"
  public static let themeChanged = "codepi:theme-changed"
  public static let terminalEvent = "codepi:terminal-event"
  public static let previewEvent = "codepi:preview-event"
}
