/**
 * The single allowlist for communication across Electron's privilege boundary.
 * Keeping channel names here prevents the main process and preload bridge from
 * silently drifting apart as the API evolves.
 */
export const ipcChannels = {
  bootstrap: 'codepi:bootstrap',
  addProject: 'codepi:add-project',
  toggleProject: 'codepi:toggle-project',
  createThread: 'codepi:create-thread',
  deleteThread: 'codepi:delete-thread',
  selectThread: 'codepi:select-thread',
  openThread: 'codepi:open-thread',
  restartThread: 'codepi:restart-thread',
  restartThreadWithoutCapabilities: 'codepi:restart-thread-without-capabilities',
  sendMessage: 'codepi:send-message',
  abortThread: 'codepi:abort-thread',
  setModel: 'codepi:set-model',
  setThinkingLevel: 'codepi:set-thinking-level',
  getCapabilities: 'codepi:get-capabilities',
  setCapabilityEnabled: 'codepi:set-capability-enabled',
  getCommands: 'codepi:get-commands',
  compactThread: 'codepi:compact-thread',
  setAutoCompaction: 'codepi:set-auto-compaction',
  setAutoRetry: 'codepi:set-auto-retry',
  getUsageDashboard: 'codepi:get-usage-dashboard',
  searchProjectFiles: 'codepi:search-project-files',
  getRecentFiles: 'codepi:get-recent-files',
  pickAttachments: 'codepi:pick-attachments',
  listPromptTemplates: 'codepi:list-prompt-templates',
  savePromptTemplate: 'codepi:save-prompt-template',
  deletePromptTemplate: 'codepi:delete-prompt-template',
  getHistory: 'codepi:get-history',
  branchThread: 'codepi:branch-thread',
  updateThread: 'codepi:update-thread',
  duplicateThread: 'codepi:duplicate-thread',
  restoreThread: 'codepi:restore-thread',
  purgeThread: 'codepi:purge-thread',
  searchThreads: 'codepi:search-threads',
  exportThread: 'codepi:export-thread',
  getChanges: 'codepi:get-changes',
  setFileStaged: 'codepi:set-file-staged',
  commit: 'codepi:commit',
  applyToMain: 'codepi:apply-to-main',
  openInEditor: 'codepi:open-in-editor',
  listWorkspaceFiles: 'codepi:list-workspace-files',
  readWorkspaceFile: 'codepi:read-workspace-file',
  openTerminal: 'codepi:open-terminal',
  writeTerminal: 'codepi:write-terminal',
  resizeTerminal: 'codepi:resize-terminal',
  closeTerminal: 'codepi:close-terminal',
  openPreview: 'codepi:open-preview',
  setPreviewBounds: 'codepi:set-preview-bounds',
  previewAction: 'codepi:preview-action',
  closePreview: 'codepi:close-preview',
  openSettings: 'codepi:open-settings',
  getSettings: 'codepi:get-settings',
  saveSettings: 'codepi:save-settings',
  validatePi: 'codepi:validate-pi',
  threadEvent: 'codepi:thread-event',
  menuAction: 'codepi:menu-action',
  themeChanged: 'codepi:theme-changed',
  terminalEvent: 'codepi:terminal-event',
  previewEvent: 'codepi:preview-event',
} as const
